const ListOfSkills = {
  communication: {
    label: "Communication",
    list: {
      1: "Listening",
      2: "Negotiation",
      3: "Nonverbal communication",
      4: "Persuasion",
      5: "Presentation",
      6: "Public speaking",
      7: "Reading body language",
      8: "Storytelling",
      9: "Verbal communication",
      10: "Visual communication",
      11: "Writing reports and proposals",
      12: "Writing skills",
    },
  },
  critical_thinking: {
    label: "Critcical Thinking",
    list: {
      1: "Adaptability",
      2: "Artistic aptitude",
      3: "Creativity",
      4: "Critical observation",
      5: "Critical thinking",
      6: "Design aptitude",
      7: "Desire to learn",
      8: "Flexibility",
      9: "Innovation",
      10: "Logical thinking",
      11: "Problem solving",
      12: "Research",
      13: "Resourcefulness",
      14: "Thinking outside the box",
      15: "Tolerance of change and uncertainty",
      16: "Troubleshooting",
      17: "Value education",
      18: "Willingness to learn",
    },
  },
  leadership: {
    label: "Leadership",
    list: {
      1: "Conflict management",
      2: "Conflict resolution",
      3: "Deal making",
      4: "Decision making",
      5: "Delegation",
      6: "Dispute resolution",
      7: "Facilitation",
      8: "Giving clear feedback",
      9: "Inspiring people",
      10: "Leadership",
      11: "Management",
      12: "Managing difficult conversations",
      13: "Managing remote/virtual teams",
      14: "Meeting management",
      15: "Mentoring",
      16: "Motivating",
      17: "Project management",
      18: "Resolving issues",
      19: "Successful coaching",
      20: "Supervising",
      21: "Talent management",
    },
  },
  teamwork: {
    label: "Teamwork",
    list: {
      1: "Accepting feedback",
      2: "Collaboration",
      3: "Customer service",
      4: "Dealing with difficult situations",
      5: "Dealing with office politics",
      6: "Disability awareness",
      7: "Diversity awareness",
      8: "Emotional intelligence",
      9: "Empathy",
      10: "Establishing interpersonal relationships",
      11: "Dealing with difficult personalities",
      12: "Intercultural competence",
      13: "Interpersonal skills",
      14: "Influence",
      15: "Networking",
      16: "Persuasion",
      17: "Self-awareness",
      18: "Selling skills",
      19: "Social skills",
      20: "Team building",
    },
  },
  work_ethic: {
    label: "Work ethic",
    list: {
      1: "Attentiveness",
      2: "Business ethics",
      3: "Competitiveness",
      4: "Dedication",
      5: "Dependability",
      6: "Following direction",
      7: "Independence",
      8: "Meeting deadlines",
      9: "Motivation",
      10: "Multitasking",
      11: "Organization",
      12: "Perseverance",
      13: "Persistence",
      14: "Planning",
      15: "Proper business etiquette",
      16: "Punctuality",
      17: "Reliability",
      18: "Resilience",
      19: "Results-oriented",
      20: "Scheduling",
      21: "Self-directed",
      22: "Self-monitoring",
      23: "Self-supervising",
      24: "Staying on task",
      25: "Strategic planning",
      26: "Time management",
      27: "Trainability",
      28: "Working well under pressure",
    },
  },
};
export default ListOfSkills;
