const ListOfJobs = {
  1: "Accountancy",
  2: "Banking",
  3: "Finance",
  4: "Business",
  5: "Consultin",
  6: "Management",
  7: "Charity",
  8: "Voluntary work",
  9: "Creative arts",
  10: "Design",
  11: "Energy",
  12: "Utilities",
  13: "Engineering",
  14: "Manufacturing",
  15: "Environment",
  16: "Agriculture",
  17: "Healthcare",
  18: "Hospitality",
  19: "Events management",
  20: "Information technology",
  21: "Law",
  22: "Law enforcement",
  23: "Security",
  24: "Leisure",
  25: "Sport",
  26: "Tourism",
  27: "Marketing",
  28: "Advertising",
  29: "Media and internet",
  30: "Property and construction",
  31: "Public services",
  32: "Administration",
  33: "Recruitment",
  34: "HR",
  35: "Retail",
  36: "Sales",
  37: "Science",
  38: "Pharmaceuticals",
  39: "Social care",
  40: "Teaching",
  41: "Education",
  42: "Transport",
  43: "Logistics",
  44: "Web development",
  45: "Data science",
  46: "Data analysis",
  47: "Software development",
};

export default ListOfJobs;
